version: "3"

services:
  app:
    build: ./
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    depends_on:
      - mongo
    command: sh -c "npm run dev"
    tty: true

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  node_modules:
  mongodb_data:
